# Generated by Django 5.1.4 on 2025-01-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(blank=True, upload_to='item/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_name',
            field=models.CharField(max_length=20),
        ),
    ]
