# Generated by Django 5.1.4 on 2025-01-14 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_feedback_created_at_alter_feedback_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Created_at',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(upload_to='item/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='User_Name',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_App.item')),
            ],
        ),
    ]
